baseURL = 'http://dylanreed.com/'
languageCode = 'en-us'
title = 'Dylan Reed'


[author]
  name = "Dylan Reed"
  headline = "An OG web3 builder, author, clown, and juggler."
  image = "https://www.gravatar.com/avatar/36aff981378cc0b408b7d1bc2f082741?s=240&d=mp"
  links = [

    { email =  { href = "contact", text = "Email me", target = "_self" } },
    { link = { href = "https://dylan.blog", text = "My blog" } },
    { github = "https://github.com/dylanreed" },
    { ethereum = { href = "https://etherscan.io/enslookup-search?search=dylanreed.eth", text = "dylanreed.eth", target = "_self" } },
    { opensea = { href = "https://opensea.io/dylanreed.eth", text = "OpenSea", target = "_self" } },
    
    { twitter = "https://twitter.com/dylanreed" },
    { instagram = "https://instagram.com/dylanreed" },
    { linkedin = "https://www.linkedin.com/in/dylannotdylan/" },
    { page = { href = "about", text = "About", target = "_self" } },
  ]